version: "2"

linters:
  default: standard
  enable:
    - dupword
    - errorlint
    - gocritic
    - gosec
    - intrange
    - misspell
    - nolintlint
    - thelper
    - unconvert
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    gosec:
      excludes:
        - G204 # subprocess launched with variable — intentional for LLVM tool invocation
        - G301 # directory permissions 0755 — standard for output directories
        - G304 # file inclusion via variable — CLI tool reads files by path by design
  exclusions:
    paths:
      - examples
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec

formatters:
  enable:
    - goimports
