version: 2

before:
  hooks:
    - go mod tidy
    - go vet ./...
    - go test ./...

builds:
  - main: ./cmd/tinybpf
    binary: tinybpf
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/kyleseneker/tinybpf/internal/cli.Version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

sboms:
  - artifacts: archive

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: kyleseneker
    name: tinybpf
  draft: false
  prerelease: auto
