// Code generated by tinybpf; DO NOT EDIT.

package loader

import (
	"fmt"

	"github.com/cilium/ebpf"
)

// Objects contains all programs and maps from the BPF object.
type Objects struct {
	Programs
	Maps
}

// Programs contains all BPF programs.
type Programs struct {
	CheckConnect4 *ebpf.Program `ebpf:"check_connect4"`
}

// Maps contains all BPF maps.
type Maps struct {
	BlockedAddrs *ebpf.Map `ebpf:"blocked_addrs"`
}

// Load loads the BPF object from objectPath and returns populated Objects.
func Load(objectPath string) (*Objects, error) {
	spec, err := ebpf.LoadCollectionSpec(objectPath)
	if err != nil {
		return nil, fmt.Errorf("load BPF spec: %w", err)
	}
	var objs Objects
	if err := spec.LoadAndAssign(&objs, nil); err != nil {
		return nil, fmt.Errorf("load and assign: %w", err)
	}
	return &objs, nil
}

// Close releases all resources held by Objects.
func (o *Objects) Close() {
	if o == nil {
		return
	}
	o.Programs.Close()
	o.Maps.Close()
}

// Close releases all programs.
func (p *Programs) Close() {
	if p.CheckConnect4 != nil {
		_ = p.CheckConnect4.Close()
	}
}

// Close releases all maps.
func (m *Maps) Close() {
	if m.BlockedAddrs != nil {
		_ = m.BlockedAddrs.Close()
	}
}
