// Package loader attaches the generated BPF objects for the cgroup-connect
// example. The type-safe loader boilerplate (Objects/Programs/Maps/Load) is
// generated by `tinybpf generate`; see connect_bpf.go.
package loader

//go:generate tinybpf generate --output connect_bpf.go --package loader ../../build/connect.bpf.o

import (
	"fmt"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
)

// Loaded holds the resources obtained after a successful load and attach.
type Loaded struct {
	Objects         *Objects
	Link            link.Link
	BlockedAddrsMap *ebpf.Map
}

// LoadAndAttach loads the eBPF collection from objectPath and attaches the
// cgroup/connect4 program to the given cgroup path.
func LoadAndAttach(objectPath, cgroupPath string) (*Loaded, error) {
	objs, err := Load(objectPath)
	if err != nil {
		return nil, err
	}

	cgLink, err := link.AttachCgroup(link.CgroupOptions{
		Path:    cgroupPath,
		Attach:  ebpf.AttachCGroupInet4Connect,
		Program: objs.CheckConnect4,
	})
	if err != nil {
		objs.Close()
		return nil, fmt.Errorf("attach cgroup/connect4: %w", err)
	}

	return &Loaded{
		Objects:         objs,
		Link:            cgLink,
		BlockedAddrsMap: objs.BlockedAddrs,
	}, nil
}

// Close detaches the cgroup program and releases all kernel resources.
func (l *Loaded) Close() {
	if l == nil {
		return
	}
	if l.Link != nil {
		_ = l.Link.Close()
	}
	if l.Objects != nil {
		l.Objects.Close()
	}
}
