// Package loader attaches the generated BPF objects for the xdp-filter
// example. The type-safe loader boilerplate (Objects/Programs/Maps/Load) is
// generated by `tinybpf generate`; see filter_bpf.go.
package loader

//go:generate tinybpf generate --output filter_bpf.go --package loader ../../build/filter.bpf.o

import (
	"fmt"
	"net"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
)

// Loaded holds the resources obtained after a successful load and attach.
type Loaded struct {
	Objects      *Objects
	Link         link.Link
	BlocklistMap *ebpf.Map
}

// LoadAndAttach loads the eBPF collection from objectPath and attaches the
// XDP program to the specified network interface.
func LoadAndAttach(objectPath, iface string) (*Loaded, error) {
	objs, err := Load(objectPath)
	if err != nil {
		return nil, err
	}

	ifObj, err := net.InterfaceByName(iface)
	if err != nil {
		objs.Close()
		return nil, fmt.Errorf("interface %q: %w", iface, err)
	}

	xdpLink, err := link.AttachXDP(link.XDPOptions{
		Program:   objs.XdpFilter,
		Interface: ifObj.Index,
	})
	if err != nil {
		objs.Close()
		return nil, fmt.Errorf("attach XDP to %s: %w", iface, err)
	}

	return &Loaded{
		Objects:      objs,
		Link:         xdpLink,
		BlocklistMap: objs.Blocklist,
	}, nil
}

// Close detaches the XDP program and releases all kernel resources.
func (l *Loaded) Close() {
	if l == nil {
		return
	}
	if l.Link != nil {
		_ = l.Link.Close()
	}
	if l.Objects != nil {
		l.Objects.Close()
	}
}
