package codegen

import (
	"strings"
	"testing"
)

func TestExportedName(t *testing.T) {
	tests := []struct {
		in   string
		want string
	}{
		{"kprobe_openat", "KprobeOpenat"},
		{"xdp_filter", "XdpFilter"},
		{"events", "Events"},
		{"blocked_ports", "BlockedPorts"},
		{"counters", "Counters"},
		{"raw_tracepoint_sched_process_exec", "RawTracepointSchedProcessExec"},
		{"lsm_file_open", "LsmFileOpen"},
		{"a_b_c", "ABC"},
	}
	for _, tt := range tests {
		t.Run(tt.in, func(t *testing.T) {
			got := exportedName(tt.in)
			if got != tt.want {
				t.Errorf("exportedName(%q) = %q, want %q", tt.in, got, tt.want)
			}
		})
	}
}

func TestGenerate(t *testing.T) {
	info := &ELFInfo{
		Programs: []string{"kprobe_openat", "xdp_filter"},
		Maps:     []string{"blocklist", "events"},
	}

	src, err := Generate("loader", info)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	text := string(src)

	contains := []string{
		"package loader",
		"// Code generated by tinybpf; DO NOT EDIT.",
		`KprobeOpenat`,
		`*ebpf.Program`,
		`ebpf:"kprobe_openat"`,
		`XdpFilter`,
		`ebpf:"xdp_filter"`,
		`Blocklist`,
		`*ebpf.Map`,
		`ebpf:"blocklist"`,
		`Events`,
		`ebpf:"events"`,
		"func Load(objectPath string)",
		"spec.LoadAndAssign",
		"func (o *Objects) Close()",
		"func (p *Programs) Close()",
		"func (m *Maps) Close()",
		"type Objects struct",
		"type Programs struct",
		"type Maps struct",
	}

	for _, s := range contains {
		if !strings.Contains(text, s) {
			t.Errorf("generated source missing %q", s)
		}
	}
}

func TestGenerateNoMaps(t *testing.T) {
	info := &ELFInfo{
		Programs: []string{"handler"},
	}

	src, err := Generate("main", info)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	text := string(src)
	if !strings.Contains(text, "type Maps struct") {
		t.Error("missing Maps struct")
	}
	if !strings.Contains(text, `Handler *ebpf.Program`) {
		t.Error("missing Handler program field")
	}
}

func TestGenerateNameCollision(t *testing.T) {
	info := &ELFInfo{
		Programs: []string{"a_b"},
		Maps:     []string{"a_b"},
	}

	_, err := Generate("test", info)
	if err == nil {
		t.Fatal("expected name collision error")
	}
	if !strings.Contains(err.Error(), "name collision") {
		t.Fatalf("expected name collision error, got: %v", err)
	}
}

func TestGenerateSingleProgram(t *testing.T) {
	info := &ELFInfo{
		Programs: []string{"trace_openat2"},
		Maps:     []string{"events"},
	}

	src, err := Generate("loader", info)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	text := string(src)
	if !strings.Contains(text, `TraceOpenat2 *ebpf.Program`) {
		t.Error("missing TraceOpenat2 program field")
	}
}
