package codegen

import (
	"encoding/binary"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestExportedName(t *testing.T) {
	tests := []struct {
		in   string
		want string
	}{
		{"kprobe_openat", "KprobeOpenat"},
		{"xdp_filter", "XdpFilter"},
		{"events", "Events"},
		{"blocked_ports", "BlockedPorts"},
		{"counters", "Counters"},
		{"raw_tracepoint_sched_process_exec", "RawTracepointSchedProcessExec"},
		{"lsm_file_open", "LsmFileOpen"},
		{"a_b_c", "ABC"},
		{"__leading_underscores", "LeadingUnderscores"},
		{"trailing__double", "TrailingDouble"},
		{"0init", "0init"},
		{"123_bad", "123Bad"},
		{"Already_upper", "AlreadyUpper"},
	}
	for _, tt := range tests {
		t.Run(tt.in, func(t *testing.T) {
			got := exportedName(tt.in)
			if got != tt.want {
				t.Errorf("exportedName(%q) = %q, want %q", tt.in, got, tt.want)
			}
		})
	}
}

func TestGenerate(t *testing.T) {
	tests := []struct {
		name     string
		pkg      string
		info     *ELFInfo
		contains []string
		wantErr  string
	}{
		{
			name: "two programs and two maps",
			pkg:  "loader",
			info: &ELFInfo{
				Programs: []string{"kprobe_openat", "xdp_filter"},
				Maps:     []string{"blocklist", "events"},
			},
			contains: []string{
				"package loader",
				"// Code generated by tinybpf; DO NOT EDIT.",
				"KprobeOpenat",
				`ebpf:"kprobe_openat"`,
				"XdpFilter",
				`ebpf:"xdp_filter"`,
				"Blocklist",
				`ebpf:"blocklist"`,
				"Events",
				`ebpf:"events"`,
				"func Load(objectPath string)",
				"spec.LoadAndAssign",
				"func (o *Objects) Close()",
				"func (p *Programs) Close()",
				"func (m *Maps) Close()",
				"type Objects struct",
				"type Programs struct",
				"type Maps struct",
			},
		},
		{
			name: "single program no maps",
			pkg:  "main",
			info: &ELFInfo{
				Programs: []string{"handler"},
			},
			contains: []string{
				"package main",
				"type Maps struct",
				`Handler *ebpf.Program`,
			},
		},
		{
			name: "single program single map",
			pkg:  "loader",
			info: &ELFInfo{
				Programs: []string{"trace_openat2"},
				Maps:     []string{"events"},
			},
			contains: []string{
				`TraceOpenat2 *ebpf.Program`,
				`Events *ebpf.Map`,
				"p.TraceOpenat2.Close()",
				"m.Events.Close()",
			},
		},
		{
			name: "name collision between program and map",
			pkg:  "test",
			info: &ELFInfo{
				Programs: []string{"a_b"},
				Maps:     []string{"a_b"},
			},
			wantErr: "name collision",
		},
		{
			name: "name collision between programs",
			pkg:  "test",
			info: &ELFInfo{
				Programs: []string{"a_b", "a_b"},
			},
			wantErr: "name collision",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			src, err := Generate(tt.pkg, tt.info)
			if tt.wantErr != "" {
				if err == nil {
					t.Fatal("expected error")
				}
				if !strings.Contains(err.Error(), tt.wantErr) {
					t.Fatalf("expected %q in error, got: %v", tt.wantErr, err)
				}
				return
			}
			if err != nil {
				t.Fatalf("Generate failed: %v", err)
			}
			text := string(src)
			for _, s := range tt.contains {
				if !strings.Contains(text, s) {
					t.Errorf("generated source missing %q", s)
				}
			}
		})
	}
}

// testBPFELF builds a minimal valid BPF ELF with the given program and map symbols.
func testBPFELF(t *testing.T, progNames, mapNames []string) string {
	t.Helper()

	// String table: null + ".text" + ".maps" + ".symtab" + ".strtab" + ".shstrtab" + symbol names
	shstrtab := "\x00.text\x00.maps\x00.symtab\x00.strtab\x00.shstrtab\x00"
	for len(shstrtab)%8 != 0 {
		shstrtab += "\x00"
	}

	// Symbol string table
	symstrtab := "\x00"
	symNameOffsets := make(map[string]int)
	for _, name := range progNames {
		symNameOffsets[name] = len(symstrtab)
		symstrtab += name + "\x00"
	}
	for _, name := range mapNames {
		symNameOffsets[name] = len(symstrtab)
		symstrtab += name + "\x00"
	}
	for len(symstrtab)%8 != 0 {
		symstrtab += "\x00"
	}

	code := []byte{0x95, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00} // BPF exit
	mapData := make([]byte, 8)                                       // dummy map data

	// Layout: header(64) | code | mapData | symstrtab | symtab | shstrtab | sections
	off := uint64(64)
	codeOff := off
	off += uint64(len(code))
	mapDataOff := off
	off += uint64(len(mapData))
	symstrtabOff := off
	off += uint64(len(symstrtab))
	symtabOff := off

	// Build symbol table: null sym + prog syms + map syms
	nullSym := make([]byte, 24)
	var syms []byte
	syms = append(syms, nullSym...)

	textSectionIdx := uint16(1) // .text is section 1
	mapsSectionIdx := uint16(2) // .maps is section 2

	for _, name := range progNames {
		sym := make([]byte, 24)
		binary.LittleEndian.PutUint32(sym[0:4], uint32(symNameOffsets[name]))
		sym[4] = 0x12 // STT_FUNC | STB_GLOBAL
		binary.LittleEndian.PutUint16(sym[6:8], textSectionIdx)
		syms = append(syms, sym...)
	}
	for _, name := range mapNames {
		sym := make([]byte, 24)
		binary.LittleEndian.PutUint32(sym[0:4], uint32(symNameOffsets[name]))
		sym[4] = 0x11 // STT_OBJECT | STB_GLOBAL
		binary.LittleEndian.PutUint16(sym[6:8], mapsSectionIdx)
		syms = append(syms, sym...)
	}

	off += uint64(len(syms))
	shstrtabOff2 := off
	off += uint64(len(shstrtab))
	shOff := off

	numSyms := 1 + len(progNames) + len(mapNames)
	strtabIdx := uint32(3) // .strtab is section 3

	makeSH := func(nameOff int, shType uint32, flags uint64, shOffset, size uint64, link, info uint32, entsize uint64) []byte {
		sh := make([]byte, 64)
		binary.LittleEndian.PutUint32(sh[0:4], uint32(nameOff))
		binary.LittleEndian.PutUint32(sh[4:8], shType)
		binary.LittleEndian.PutUint64(sh[8:16], flags)
		binary.LittleEndian.PutUint64(sh[24:32], shOffset)
		binary.LittleEndian.PutUint64(sh[32:40], size)
		binary.LittleEndian.PutUint32(sh[40:44], link)
		binary.LittleEndian.PutUint32(sh[44:48], info)
		binary.LittleEndian.PutUint64(sh[48:56], 8)
		binary.LittleEndian.PutUint64(sh[56:64], entsize)
		return sh
	}

	// Section name offsets in shstrtab
	textNameOff := 1   // ".text"
	mapsNameOff := 7   // ".maps"
	symtabNameOff := 13 // ".symtab"
	strtabNameOff := 21 // ".strtab"
	shstrtabNameOff := 29 // ".shstrtab"

	var sections []byte
	sections = append(sections, makeSH(0, 0, 0, 0, 0, 0, 0, 0)...)                                                         // 0: null
	sections = append(sections, makeSH(textNameOff, 1, 6, codeOff, uint64(len(code)), 0, 0, 0)...)                          // 1: .text (PROGBITS | EXECINSTR)
	sections = append(sections, makeSH(mapsNameOff, 1, 2, mapDataOff, uint64(len(mapData)), 0, 0, 0)...)                    // 2: .maps (PROGBITS | ALLOC)
	sections = append(sections, makeSH(strtabNameOff, 3, 0, symstrtabOff, uint64(len(symstrtab)), 0, 0, 0)...)              // 3: .strtab
	sections = append(sections, makeSH(symtabNameOff, 2, 0, symtabOff, uint64(len(syms)), strtabIdx, uint32(1), 24)...)     // 4: .symtab
	sections = append(sections, makeSH(shstrtabNameOff, 3, 0, shstrtabOff2, uint64(len(shstrtab)), 0, 0, 0)...)             // 5: .shstrtab

	_ = numSyms

	hdr := make([]byte, 64)
	copy(hdr[0:4], []byte{0x7f, 'E', 'L', 'F'})
	hdr[4] = 2                                      // ELFCLASS64
	hdr[5] = 1                                      // ELFDATA2LSB
	hdr[6] = 1                                      // EV_CURRENT
	binary.LittleEndian.PutUint16(hdr[16:18], 1)    // ET_REL
	binary.LittleEndian.PutUint16(hdr[18:20], 0xF7) // EM_BPF
	binary.LittleEndian.PutUint32(hdr[20:24], 1)    // EV_CURRENT
	binary.LittleEndian.PutUint16(hdr[52:54], 64)   // e_ehsize
	binary.LittleEndian.PutUint16(hdr[58:60], 64)   // e_shentsize
	binary.LittleEndian.PutUint64(hdr[40:48], shOff)
	binary.LittleEndian.PutUint16(hdr[60:62], 6)    // e_shnum
	binary.LittleEndian.PutUint16(hdr[62:64], 5)    // e_shstrndx

	var out []byte
	out = append(out, hdr...)
	out = append(out, code...)
	out = append(out, mapData...)
	out = append(out, []byte(symstrtab)...)
	out = append(out, syms...)
	out = append(out, []byte(shstrtab)...)
	out = append(out, sections...)

	p := filepath.Join(t.TempDir(), "test.bpf.o")
	if err := os.WriteFile(p, out, 0o644); err != nil {
		t.Fatal(err)
	}
	return p
}

func TestExtractELFInfo(t *testing.T) {
	tests := []struct {
		name         string
		setup        func(t *testing.T) string
		wantProgs    []string
		wantMaps     []string
		wantErr      string
	}{
		{
			name: "single program and map",
			setup: func(t *testing.T) string {
				t.Helper()
				return testBPFELF(t, []string{"xdp_filter"}, []string{"blocklist"})
			},
			wantProgs: []string{"xdp_filter"},
			wantMaps:  []string{"blocklist"},
		},
		{
			name: "multiple programs and maps",
			setup: func(t *testing.T) string {
				t.Helper()
				return testBPFELF(t, []string{"prog_b", "prog_a"}, []string{"map_y", "map_x"})
			},
			wantProgs: []string{"prog_a", "prog_b"},
			wantMaps:  []string{"map_x", "map_y"},
		},
		{
			name: "no maps",
			setup: func(t *testing.T) string {
				t.Helper()
				return testBPFELF(t, []string{"handler"}, nil)
			},
			wantProgs: []string{"handler"},
		},
		{
			name: "no programs",
			setup: func(t *testing.T) string {
				t.Helper()
				return testBPFELF(t, nil, []string{"my_map"})
			},
			wantErr: "no BPF programs found",
		},
		{
			name: "non-existent file",
			setup: func(t *testing.T) string {
				t.Helper()
				return filepath.Join(t.TempDir(), "does-not-exist.o")
			},
			wantErr: "open ELF",
		},
		{
			name: "not an ELF",
			setup: func(t *testing.T) string {
				t.Helper()
				p := filepath.Join(t.TempDir(), "bad.o")
				os.WriteFile(p, []byte("not an elf"), 0o644)
				return p
			},
			wantErr: "open ELF",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			path := tt.setup(t)
			info, err := ExtractELFInfo(path)
			if tt.wantErr != "" {
				if err == nil {
					t.Fatal("expected error")
				}
				if !strings.Contains(err.Error(), tt.wantErr) {
					t.Fatalf("expected %q in error, got: %v", tt.wantErr, err)
				}
				return
			}
			if err != nil {
				t.Fatalf("ExtractELFInfo failed: %v", err)
			}
			if len(info.Programs) != len(tt.wantProgs) {
				t.Fatalf("programs: got %v, want %v", info.Programs, tt.wantProgs)
			}
			for i, name := range tt.wantProgs {
				if info.Programs[i] != name {
					t.Errorf("programs[%d]: got %q, want %q", i, info.Programs[i], name)
				}
			}
			if len(info.Maps) != len(tt.wantMaps) {
				t.Fatalf("maps: got %v, want %v", info.Maps, tt.wantMaps)
			}
			for i, name := range tt.wantMaps {
				if info.Maps[i] != name {
					t.Errorf("maps[%d]: got %q, want %q", i, info.Maps[i], name)
				}
			}
		})
	}
}
