// Package codegen generates type-safe Go loader code from compiled BPF ELF objects.
package codegen

import (
	"debug/elf"
	"fmt"
	"go/format"
	"sort"
	"strings"
)

// ELFInfo holds the programs and maps extracted from a BPF ELF object.
type ELFInfo struct {
	Programs []string
	Maps     []string
}

// ExtractELFInfo reads a BPF ELF object and returns its program and map symbol names.
func ExtractELFInfo(path string) (*ELFInfo, error) {
	f, err := elf.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open ELF %q: %w", path, err)
	}
	defer func() { _ = f.Close() }()

	syms, err := f.Symbols()
	if err != nil {
		return nil, fmt.Errorf("read symbols from %q: %w", path, err)
	}

	mapsSectionIdx := -1
	for i, s := range f.Sections {
		if s.Name == ".maps" {
			mapsSectionIdx = i
			break
		}
	}

	var info ELFInfo
	for _, sym := range syms {
		if sym.Section == elf.SHN_UNDEF || int(sym.Section) >= len(f.Sections) {
			continue
		}
		sec := f.Sections[sym.Section]

		bind := elf.ST_BIND(sym.Info)
		typ := elf.ST_TYPE(sym.Info)

		if bind == elf.STB_GLOBAL && typ == elf.STT_FUNC &&
			sec.Type == elf.SHT_PROGBITS && sec.Flags&elf.SHF_EXECINSTR != 0 {
			info.Programs = append(info.Programs, sym.Name)
		}

		if mapsSectionIdx >= 0 && int(sym.Section) == mapsSectionIdx {
			info.Maps = append(info.Maps, sym.Name)
		}
	}

	sort.Strings(info.Programs)
	sort.Strings(info.Maps)

	if len(info.Programs) == 0 {
		return nil, fmt.Errorf("no BPF programs found in %q", path)
	}

	return &info, nil
}

// Generate produces formatted Go source code for loading the BPF objects.
func Generate(pkg string, info *ELFInfo, embedPath string) ([]byte, error) {
	if err := checkNameCollisions(info); err != nil {
		return nil, err
	}

	var b strings.Builder
	writeHeader(&b, pkg, embedPath)
	if embedPath != "" {
		writeEmbed(&b, embedPath)
	}
	writeObjectsStruct(&b)
	writeProgramsStruct(&b, info.Programs)
	writeMapsStruct(&b, info.Maps)
	if embedPath != "" {
		writeEmbedLoadFunc(&b)
	} else {
		writeLoadFunc(&b)
	}
	writeObjectsClose(&b)
	writeProgramsClose(&b, info.Programs)
	writeMapsClose(&b, info.Maps)

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return src, nil
}

// exportedName converts a snake_case symbol name to PascalCase.
func exportedName(s string) string {
	var b strings.Builder
	for _, part := range strings.Split(s, "_") {
		if part == "" {
			continue
		}
		c := part[0]
		if c >= 'a' && c <= 'z' {
			b.WriteByte(c - 'a' + 'A')
		} else {
			b.WriteByte(c)
		}
		b.WriteString(part[1:])
	}
	return b.String()
}

func checkNameCollisions(info *ELFInfo) error {
	seen := make(map[string]string)
	for _, name := range info.Programs {
		exported := exportedName(name)
		if prev, ok := seen[exported]; ok {
			return fmt.Errorf("name collision: %q and %q both map to %q", prev, name, exported)
		}
		seen[exported] = name
	}
	for _, name := range info.Maps {
		exported := exportedName(name)
		if prev, ok := seen[exported]; ok {
			return fmt.Errorf("name collision: %q and %q both map to %q", prev, name, exported)
		}
		seen[exported] = name
	}
	return nil
}

func writeHeader(b *strings.Builder, pkg, embedPath string) {
	fmt.Fprintf(b, "// Code generated by tinybpf; DO NOT EDIT.\n\n")
	fmt.Fprintf(b, "package %s\n\n", pkg)
	fmt.Fprintf(b, "import (\n")
	if embedPath != "" {
		fmt.Fprintf(b, "\t\"bytes\"\n")
		fmt.Fprintf(b, "\t_ \"embed\"\n")
	}
	fmt.Fprintf(b, "\t\"fmt\"\n\n")
	fmt.Fprintf(b, "\t\"github.com/cilium/ebpf\"\n")
	fmt.Fprintf(b, ")\n\n")
}

func writeEmbed(b *strings.Builder, embedPath string) {
	fmt.Fprintf(b, "//go:embed %s\n", embedPath)
	fmt.Fprintf(b, "var _bpfBytes []byte\n\n")
}

func writeEmbedLoadFunc(b *strings.Builder) {
	fmt.Fprintf(b, "// Load loads the embedded BPF object and returns populated Objects.\n")
	fmt.Fprintf(b, "func Load() (*Objects, error) {\n")
	fmt.Fprintf(b, "\tspec, err := ebpf.LoadCollectionSpecFromReader(bytes.NewReader(_bpfBytes))\n")
	fmt.Fprintf(b, "\tif err != nil {\n")
	fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(\"load BPF spec: %%w\", err)\n")
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "\tvar objs Objects\n")
	fmt.Fprintf(b, "\tif err := spec.LoadAndAssign(&objs, nil); err != nil {\n")
	fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(\"load and assign: %%w\", err)\n")
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "\treturn &objs, nil\n")
	fmt.Fprintf(b, "}\n\n")
}

func writeObjectsStruct(b *strings.Builder) {
	fmt.Fprintf(b, "// Objects contains all programs and maps from the BPF object.\n")
	fmt.Fprintf(b, "type Objects struct {\n")
	fmt.Fprintf(b, "\tPrograms\n")
	fmt.Fprintf(b, "\tMaps\n")
	fmt.Fprintf(b, "}\n\n")
}

func writeProgramsStruct(b *strings.Builder, programs []string) {
	fmt.Fprintf(b, "// Programs contains all BPF programs.\n")
	fmt.Fprintf(b, "type Programs struct {\n")
	for _, name := range programs {
		fmt.Fprintf(b, "\t%s *ebpf.Program `ebpf:\"%s\"`\n", exportedName(name), name)
	}
	fmt.Fprintf(b, "}\n\n")
}

func writeMapsStruct(b *strings.Builder, maps []string) {
	fmt.Fprintf(b, "// Maps contains all BPF maps.\n")
	fmt.Fprintf(b, "type Maps struct {\n")
	for _, name := range maps {
		fmt.Fprintf(b, "\t%s *ebpf.Map `ebpf:\"%s\"`\n", exportedName(name), name)
	}
	fmt.Fprintf(b, "}\n\n")
}

func writeLoadFunc(b *strings.Builder) {
	fmt.Fprintf(b, "// Load loads the BPF object from objectPath and returns populated Objects.\n")
	fmt.Fprintf(b, "func Load(objectPath string) (*Objects, error) {\n")
	fmt.Fprintf(b, "\tspec, err := ebpf.LoadCollectionSpec(objectPath)\n")
	fmt.Fprintf(b, "\tif err != nil {\n")
	fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(\"load BPF spec: %%w\", err)\n")
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "\tvar objs Objects\n")
	fmt.Fprintf(b, "\tif err := spec.LoadAndAssign(&objs, nil); err != nil {\n")
	fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(\"load and assign: %%w\", err)\n")
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "\treturn &objs, nil\n")
	fmt.Fprintf(b, "}\n\n")
}

func writeObjectsClose(b *strings.Builder) {
	fmt.Fprintf(b, "// Close releases all resources held by Objects.\n")
	fmt.Fprintf(b, "func (o *Objects) Close() {\n")
	fmt.Fprintf(b, "\tif o == nil {\n")
	fmt.Fprintf(b, "\t\treturn\n")
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "\to.Programs.Close()\n")
	fmt.Fprintf(b, "\to.Maps.Close()\n")
	fmt.Fprintf(b, "}\n\n")
}

func writeProgramsClose(b *strings.Builder, programs []string) {
	fmt.Fprintf(b, "// Close releases all programs.\n")
	fmt.Fprintf(b, "func (p *Programs) Close() {\n")
	for _, name := range programs {
		fmt.Fprintf(b, "\tif p.%s != nil {\n", exportedName(name))
		fmt.Fprintf(b, "\t\t_ = p.%s.Close()\n", exportedName(name))
		fmt.Fprintf(b, "\t}\n")
	}
	fmt.Fprintf(b, "}\n\n")
}

func writeMapsClose(b *strings.Builder, maps []string) {
	fmt.Fprintf(b, "// Close releases all maps.\n")
	fmt.Fprintf(b, "func (m *Maps) Close() {\n")
	for _, name := range maps {
		fmt.Fprintf(b, "\tif m.%s != nil {\n", exportedName(name))
		fmt.Fprintf(b, "\t\t_ = m.%s.Close()\n", exportedName(name))
		fmt.Fprintf(b, "\t}\n")
	}
	fmt.Fprintf(b, "}\n")
}
