// Package loader attaches the generated BPF objects for the tc-filter
// example. The type-safe loader boilerplate (Objects/Programs/Maps/Load) is
// generated by `tinybpf generate`; see filter_bpf.go.
package loader

//go:generate tinybpf generate --output filter_bpf.go --package loader ../../build/filter.bpf.o

import (
	"encoding/binary"
	"fmt"
	"net"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
)

// Loaded holds the resources obtained after a successful load and attach.
type Loaded struct {
	Objects *Objects
	Link    link.Link
}

// LoadAndAttach loads the eBPF collection from objectPath, attaches the TC
// classifier to the ingress of iface, and populates the blocked_ports map
// with the given port in network byte order.
func LoadAndAttach(objectPath, iface string, port uint16) (*Loaded, error) {
	objs, err := Load(objectPath)
	if err != nil {
		return nil, err
	}

	ifObj, err := net.InterfaceByName(iface)
	if err != nil {
		objs.Close()
		return nil, fmt.Errorf("interface %q: %w", iface, err)
	}

	tcLink, err := link.AttachTCX(link.TCXOptions{
		Interface: ifObj.Index,
		Program:   objs.ClassifyIngress,
		Attach:    ebpf.AttachTCXIngress,
	})
	if err != nil {
		objs.Close()
		return nil, fmt.Errorf("attach TC classifier to %s ingress: %w", iface, err)
	}

	portBE := make([]byte, 2)
	binary.BigEndian.PutUint16(portBE, port)
	val := uint8(1)
	if err := objs.BlockedPorts.Put(portBE, val); err != nil {
		_ = tcLink.Close()
		objs.Close()
		return nil, fmt.Errorf("populate blocked_ports map with port %d: %w", port, err)
	}

	return &Loaded{
		Objects: objs,
		Link:    tcLink,
	}, nil
}

// Close detaches the TC classifier and releases all kernel resources.
func (l *Loaded) Close() {
	if l == nil {
		return
	}
	if l.Link != nil {
		_ = l.Link.Close()
	}
	if l.Objects != nil {
		l.Objects.Close()
	}
}
