//go:build ignore

// gen.go generates bpfhelpers_gen.go from the kernel's bpf.h header.
//
// Usage:
//
//	go run gen.go [-version v6.12] [-file path/to/bpf.h]
package main

import (
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
)

const headerURLTemplate = "https://raw.githubusercontent.com/torvalds/linux/%s/include/uapi/linux/bpf.h"

var reFuncEntry = regexp.MustCompile(`FN\((\w+),\s*(\d+)`)

type helper struct {
	Name string
	ID   int
}

func main() {
	version := flag.String("version", "v6.12", "kernel git tag to fetch bpf.h from")
	file := flag.String("file", "", "local bpf.h file path (overrides -version)")
	flag.Parse()

	src, err := readHeader(*version, *file)
	if err != nil {
		log.Fatal(err)
	}

	helpers, err := parseHelpers(src)
	if err != nil {
		log.Fatal(err)
	}

	if err := writeGenerated(helpers, *version); err != nil {
		log.Fatal(err)
	}

	fmt.Fprintf(os.Stderr, "generated bpfhelpers_gen.go: %d helpers from kernel %s\n", len(helpers), *version)
}

// readHeader fetches bpf.h from GitHub for the given kernel tag, or reads a local file.
func readHeader(version, filePath string) (string, error) {
	if filePath != "" {
		b, err := os.ReadFile(filePath)
		return string(b), err
	}

	url := fmt.Sprintf(headerURLTemplate, version)
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		return "", fmt.Errorf("fetching %s: %w", url, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("fetching %s: HTTP %d", url, resp.StatusCode)
	}
	b, err := io.ReadAll(resp.Body)
	return string(b), err
}

// parseHelpers extracts FN(name, id) entries from the ___BPF_FUNC_MAPPER macro.
func parseHelpers(src string) ([]helper, error) {
	start := strings.Index(src, "___BPF_FUNC_MAPPER(FN")
	if start < 0 {
		return nil, fmt.Errorf("___BPF_FUNC_MAPPER macro not found in header")
	}

	block := src[start:]
	var end int
	for i, line := range strings.Split(block, "\n") {
		if i == 0 {
			continue
		}
		if !strings.HasSuffix(strings.TrimSpace(line), `\`) {
			end = i
			break
		}
	}
	if end == 0 {
		return nil, fmt.Errorf("could not find end of ___BPF_FUNC_MAPPER macro")
	}

	lines := strings.Split(block, "\n")[:end+1]
	var helpers []helper
	for _, line := range lines {
		m := reFuncEntry.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		name := m[1]
		id, _ := strconv.Atoi(m[2])
		if name == "unspec" {
			continue
		}
		helpers = append(helpers, helper{Name: name, ID: id})
	}

	if len(helpers) == 0 {
		return nil, fmt.Errorf("no helper entries found in ___BPF_FUNC_MAPPER")
	}

	sort.Slice(helpers, func(i, j int) bool { return helpers[i].ID < helpers[j].ID })
	return helpers, nil
}

// writeGenerated emits bpfhelpers_gen.go with the bpfHelperNames array.
func writeGenerated(helpers []helper, version string) error {
	maxID := helpers[len(helpers)-1].ID
	idWidth := len(strconv.Itoa(maxID))

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by gen.go from kernel %s; DO NOT EDIT.\n\n", version)
	b.WriteString("package transform\n\n")
	b.WriteString("// bpfHelperNames lists all BPF helper names from the kernel's ___BPF_FUNC_MAPPER enum, indexed by ID.\n")
	fmt.Fprintf(&b, "var bpfHelperNames = [%d]string{\n", maxID+1)
	for _, h := range helpers {
		pad := strings.Repeat(" ", idWidth-len(strconv.Itoa(h.ID)))
		fmt.Fprintf(&b, "\t%d:%s %q,\n", h.ID, pad, h.Name)
	}
	b.WriteString("}\n")

	return os.WriteFile("bpfhelpers_gen.go", []byte(b.String()), 0o644)
}
