// Package loader attaches the generated BPF objects for the rawtp-sched
// example. The type-safe loader boilerplate (Objects/Programs/Maps/Load) is
// generated by `tinybpf generate`; see sched_bpf.go.
package loader

//go:generate tinybpf generate --output sched_bpf.go --package loader ../../build/sched.bpf.o

import (
	"fmt"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
)

// Loaded holds the resources obtained after a successful load and attach.
type Loaded struct {
	Objects   *Objects
	Link      link.Link
	EventsMap *ebpf.Map
}

// LoadAndAttach loads the eBPF object and attaches to the raw tracepoint.
func LoadAndAttach(objectPath string) (*Loaded, error) {
	objs, err := Load(objectPath)
	if err != nil {
		return nil, err
	}

	tp, err := link.AttachRawTracepoint(link.RawTracepointOptions{
		Name:    "sched_process_exec",
		Program: objs.RawTracepointSchedProcessExec,
	})
	if err != nil {
		objs.Close()
		return nil, fmt.Errorf("attach raw tracepoint: %w", err)
	}

	return &Loaded{
		Objects:   objs,
		Link:      tp,
		EventsMap: objs.Events,
	}, nil
}

// Close detaches the raw tracepoint and releases all kernel resources.
func (l *Loaded) Close() {
	if l == nil {
		return
	}
	if l.Link != nil {
		_ = l.Link.Close()
	}
	if l.Objects != nil {
		l.Objects.Close()
	}
}
