// Package loader attaches the generated BPF objects for the lsm-file-open
// example. The type-safe loader boilerplate (Objects/Programs/Maps/Load) is
// generated by `tinybpf generate`; see lsm_bpf.go.
package loader

//go:generate tinybpf generate --output lsm_bpf.go --package loader ../../build/lsm.bpf.o

import (
	"fmt"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
)

// Loaded holds the resources obtained after a successful load and attach.
type Loaded struct {
	Objects   *Objects
	Link      link.Link
	EventsMap *ebpf.Map
}

// LoadAndAttach loads the eBPF collection from objectPath and attaches the
// LSM file_open hook.
func LoadAndAttach(objectPath string) (*Loaded, error) {
	objs, err := Load(objectPath)
	if err != nil {
		return nil, err
	}

	lsmLink, err := link.AttachLSM(link.LSMOptions{
		Program: objs.LsmFileOpen,
	})
	if err != nil {
		objs.Close()
		return nil, fmt.Errorf("attach LSM: %w", err)
	}

	return &Loaded{
		Objects:   objs,
		Link:      lsmLink,
		EventsMap: objs.Events,
	}, nil
}

// Close detaches the LSM program and releases all kernel resources.
func (l *Loaded) Close() {
	if l == nil {
		return
	}
	if l.Link != nil {
		_ = l.Link.Close()
	}
	if l.Objects != nil {
		l.Objects.Close()
	}
}
