// Package loader attaches the generated BPF objects for the kprobe-openat
// example. The type-safe loader boilerplate (Objects/Programs/Maps/Load) is
// generated by `tinybpf generate`; see openat_bpf.go.
package loader

//go:generate tinybpf generate --output openat_bpf.go --package loader ../../build/openat.bpf.o

import (
	"fmt"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
)

// Loaded holds the resources obtained after a successful load and attach.
type Loaded struct {
	Objects   *Objects
	Link      link.Link
	EventsMap *ebpf.Map
}

// LoadAndAttach loads the eBPF collection from objectPath and attaches the
// kprobe program to do_sys_openat2.
func LoadAndAttach(objectPath string) (*Loaded, error) {
	objs, err := Load(objectPath)
	if err != nil {
		return nil, err
	}

	kp, err := link.Kprobe("do_sys_openat2", objs.KprobeOpenat, nil)
	if err != nil {
		objs.Close()
		return nil, fmt.Errorf("attach kprobe: %w", err)
	}

	return &Loaded{
		Objects:   objs,
		Link:      kp,
		EventsMap: objs.Events,
	}, nil
}

// Close detaches the kprobe program and releases all kernel resources.
func (l *Loaded) Close() {
	if l == nil {
		return
	}
	if l.Link != nil {
		_ = l.Link.Close()
	}
	if l.Objects != nil {
		l.Objects.Close()
	}
}
