// Package loader attaches the generated BPF objects for the percpu-counter
// example. The type-safe loader boilerplate (Objects/Programs/Maps/Load) is
// generated by `tinybpf generate`; see counter_bpf.go.
package loader

//go:generate tinybpf generate --output counter_bpf.go --package loader ../../build/counter.bpf.o

import (
	"fmt"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
)

// Loaded holds the resources obtained after a successful load and attach.
type Loaded struct {
	Objects     *Objects
	Link        link.Link
	CountersMap *ebpf.Map
}

// LoadAndAttach loads the eBPF collection from objectPath and attaches the
// tracepoint program to raw_syscalls/sys_enter.
func LoadAndAttach(objectPath string) (*Loaded, error) {
	objs, err := Load(objectPath)
	if err != nil {
		return nil, err
	}

	tp, err := link.Tracepoint("raw_syscalls", "sys_enter", objs.TracepointSyscallsSysEnter, nil)
	if err != nil {
		objs.Close()
		return nil, fmt.Errorf("attach tracepoint: %w", err)
	}

	return &Loaded{
		Objects:     objs,
		Link:        tp,
		CountersMap: objs.Counters,
	}, nil
}

// Close detaches the tracepoint program and releases all kernel resources.
func (l *Loaded) Close() {
	if l == nil {
		return
	}
	if l.Link != nil {
		_ = l.Link.Close()
	}
	if l.Objects != nil {
		l.Objects.Close()
	}
}
